#!/bin/bash

if [ "${1}" == "clean" ]; then
  rm -rf alpha.pdb alpha.dmdgp alpha.dcd
  exit
fi

../../bin/ibp-ng -v -v \
 --input alpha.fa \
 --psf alpha.psf \
 --dmdgp alpha.dmdgp \
 --output alpha.pdb \
 --format pdb \
 --restraints alpha.res \
 --topology ../../lib/ibp-protein.top \
 --params ../../lib/ibp-protein.par \
 --reorder ../../lib/ibp-protein.ord \
 --threads 1 \
 --method dist,impr,dihe \
 --limit 1000 --branch-eps 0.04 --branch-max 128 --vdw-scale 0.5

