#!/bin/bash

if [ "${1}" == "clean" ]; then
  rm -rf alpha.psf alpha.dmdgp alpha.pdb
  exit
fi

../../bin/ibp-ng -v -v \
 --input alpha2.fa \
 --psf alpha.psf \
 --dmdgp alpha.dmdgp \
 --output alpha.pdb \
 --format pdb \
 --restraints alpha.res \
 --topology ../../lib/ibp-protein.top \
 --params ../../lib/ibp-protein.par \
 --reorder ../../lib/ibp-protein2.ord \
 --threads 1 \
 --method dist,impr,dihe \
 --limit 10000 --branch-eps 0.01 --branch-max 128 --vdw-scale 0.5

